name: Test architecture matrix
run-name: ${{ github.actor }} is doing a develop build

#        arch: [armv6l, armv7l, aarch64]
#        - arch: armv6l
#          cpu: arm1176
#          base_image: raspios_lite:latest
#          cpu_info: cpuinfo/raspberrypi_zero_w

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        image_additional_mb: 4096
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            test `uname -m` = ${{ matrix.arch }}
            grep Model /proc/cpuinfo
            #
            echo "uname -r: $(uname -r)"
            echo "uname -a: $(uname -a)"
            os_name=$(uname -s)
            echo "OS Type          : $os_name"
            machine=$(uname -m)
            echo "Machine Arch     : $machine"

            #
            OS_BITFLAG="32"
            #
            case "${os_name}" in
               *hp-hpux*)
                  ;;
               *ibm-aix*)
                  rc=`lsconf -k | grep -c 64-bit`
                  if test $rc -eq 1; then
                     OS_BITFLAG="64"
                  fi
                  ;;
               i*86*solaris*)
                  ;;
               *solaris*)
                  rc=`isainfo -v | grep -c 64-bit`
                  if test $rc -eq 1; then
                     OS_BITFLAG="64"
                  fi
                  ;;
               sparc*sunos*)
                  ;;
               Linux)
                  mach="`uname -m`"
                  if test "$mach" = "aarch64" -o "$mach" = "x86_64" -o "$mach" = "ia86" -o "$mach" = "alpha" -o "$mach" = "ppc64" -o "$mach" = "ppc64le" -o "$mach" = "s390x" -o "$mach" = "e2k" -o "$mach" = "riscv64" ; then
                     OS_BITFLAG="64"
                  fi
                  ;;
               FreeBSD|OpenBSD|NetBSD)
                  mach="`uname -m`"
                  if test "$mach" = "amd64" -o "$mach" = "sparc64" ; then
                     OS_BITFLAG="64"
                  fi
                  ;;
               Darwin)
                  os_osx_64bit=`sysctl hw.cpu64bit_capable | cut -f2 -d' '`
                  if test $os_osx_64bit -eq 1; then
                     OS_BITFLAG="64"
                  fi
                  ;;
            esac
            #
            echo "Platform Bitness : $OS_BITFLAG"
            #
            export OPT_BUILD_DIR=/sandbox/herctest
            export OPT_INSTALL_DIR="/usr/local"
            #
            export SCRIPT_DIR=/sandbox/hercules-helper
            export OPT_REGINA_DIR="Regina-REXX-3.6"
            export OPT_REGINA_TARFILE="Regina-REXX-3.6.tar.gz"
            export OPT_REGINA_URL="http://www.wrljet.com/ibm360/Regina-REXX-3.6.tar.gz"
            export GIT_REPO_HERCULES="https://github.com/SDL-Hercules-390/hyperion.git"
            export GIT_BRANCH_HERCULES="develop"
            export GIT_COMMIT_HERCULES=""
            export GIT_REPO_EXTPKGS="https://github.com/SDL-Hercules-390"
            export GIT_BRANCH_EXTPKGS=""
            #
            # reports: /sandbox
            pwd
            #
            sudo apt-get install -y git wget time ncat
            sudo apt-get install -y build-essential
            sudo apt-get install -y cmake autoconf automake flex gawk m4
            sudo apt-get install -y libltdl-dev libtool-bin libcap2-bin libbz2-dev zlib1g-dev
            #
            # Clone Hercules-Helper
            git clone https://github.com/wrljet/hercules-helper.git
            ls -l
            #
            mkdir -p $OPT_INSTALL_DIR
            mkdir -p $OPT_BUILD_DIR/hyperion
            cd $OPT_BUILD_DIR
            rm -rf hyperion || true
            #
            which rexx && true
            #export OPT_REGINA_URL="http://www.wrljet.com/ibm360/Regina-REXX-3.6.tar.gz"
            #export OPT_REGINA_TARFILE="Regina-REXX-3.6.tar.gz"
            #export OPT_REGINA_DIR="Regina-REXX-3.6"
            wget $OPT_REGINA_URL
            tar xfz "$OPT_REGINA_TARFILE"
            pwd
            # pushd $OPT_REGINA_DIR
            cd $OPT_REGINA_DIR
            #
            echo "Patching Regina 3.6 source for aarch64"
            patch -u configure -i "$SCRIPT_DIR/patches/regina-rexx-3.6.patch"
            echo "Replacing config.{guess,sub}"
            cp "$SCRIPT_DIR/patches/config.guess" ./common/
            cp "$SCRIPT_DIR/patches/config.sub" ./common/
            #
            ./configure --libdir=/usr/lib
            ./config.status --config
            make
            sudo make install
            #popd
            cd -
            #
            ldconfig
            echo "Files:"
            which rexx
            find /usr/local/include -name 'rexx*.h' 2>&1
            #
            # git clone required repos
            cd $OPT_BUILD_DIR
            rm -rf hyperion || true
            git clone -b $GIT_BRANCH_HERCULES $GIT_REPO_HERCULES
            #
            cd $OPT_BUILD_DIR
            rm -rf extpkgs
            mkdir extpkgs
            cd extpkgs/
            rm -rf *
            git clone $GIT_REPO_EXTPKGS/crypto
            git clone $GIT_REPO_EXTPKGS/decNumber
            git clone $GIT_REPO_EXTPKGS/SoftFloat
            git clone $GIT_REPO_EXTPKGS/telnet
            #
            cd $OPT_BUILD_DIR/hyperion
            #
            # Check program versions
            util/bldlvlck
            #
            # Prepare and build extpkgs
            cd $OPT_BUILD_DIR/extpkgs
            rm -rf lib/
            #
            # We do this to match the way it's done in Hercules configure
            target_cpu=$(uname -m)
            case "$target_cpu" in
                i*86|x86*)
                    hc_cv_cpu_arch=x86
                    hc_cv_pkg_lib_subdir=""
                    ;;
                amd64*)
                    hc_cv_cpu_arch=x86
                    hc_cv_pkg_lib_subdir=""
                    ;;
                aarch64*)
                    hc_cv_cpu_arch=aarch64
                    hc_cv_pkg_lib_subdir="/aarch64"
                    ;;
                arm64*)
                    hc_cv_cpu_arch=aarch64
                    hc_cv_pkg_lib_subdir="/aarch64"
                    ;;
                arm*)
                    hc_cv_cpu_arch=arm
                    hc_cv_pkg_lib_subdir="/arm"
                    ;;
                e2k*)
                    hc_cv_cpu_arch=e2k
                    hc_cv_pkg_lib_subdir="/e2k"
                    ;;
                mips*)
                    hc_cv_cpu_arch=mips
                    hc_cv_pkg_lib_subdir="/mips"
                    ;;
                ppc*|powerpc*)
                    hc_cv_cpu_arch=ppc
                    hc_cv_pkg_lib_subdir="/ppc"
                    ;;
                sparc*)
                    hc_cv_cpu_arch=sparc
                    hc_cv_pkg_lib_subdir="/sparc"
                    ;;
                s390x*)
                    hc_cv_cpu_arch=s390x
                    hc_cv_pkg_lib_subdir="/s390x"
                    ;;
                xscale*)
                    hc_cv_cpu_arch=xscale
                    hc_cv_pkg_lib_subdir="/xscale"
                    ;;
                riscv64*)
                    hc_cv_cpu_arch=riscv64
                    hc_cv_pkg_lib_subdir="/riscv64"
                    ;;
                *)
                    hc_cv_cpu_arch=unknown
                    hc_cv_pkg_lib_subdir="/unknown"
                    ;;
            esac
            #
            for pkg in crypto decNumber SoftFloat telnet; do
                echo "Building extpkg: $pkg"
            #
                mkdir -p build/${pkg}$OS_BITFLAG.Release
                cd build/${pkg}$OS_BITFLAG.Release
            #
                    # Clear CMake cache in case we've changed the options
                    rm -f CMakeCache.txt
            #
                    # e.g. OPT_CMAKE_DEFINES="-DCMAKE_C_FLAGS_RELWITHDEBINFO=\"-O3 -march=native -g\""
                    if [ ! -z "$OPT_CMAKE_DEFINES" ] ; then
                        verbose_msg "Adding CMake defines: $OPT_CMAKE_DEFINES"
                    fi
            #
            #
                    cmake_cmd= cmake $OPT_CMAKE_DEFINES -D INSTALL_PREFIX=$OPT_BUILD_DIR/extpkgs -DLIB_INSTALL_DIR=lib$hc_cv_pkg_lib_subdir $OPT_BUILD_DIR/extpkgs/$pkg
            #
                    echo $cmake_cmd
                    eval "$cmake_cmd"
            #
                    rc=$?
                    if (( $rc != 0 )); then
                        echo "ERROR: Cmake has failed! rc=$rc";
                        echo "ERROR: extpkgs not built";
                        exit 3
                    fi
            #
                    make clean
                    make -j 2 all
                    make install
                 cd -
                 pwd
            done
            #
            cd -
            pwd
            #
            mkdir -p $OPT_BUILD_DIR/hyperion/build
            cd $OPT_BUILD_DIR/hyperion/build
            #
            # Configure and build Hercules
            CFLAGS="-frecord-gcc-switches" ../configure --enable-optimization="-g -g3 -ggdb3 -O3 -march=native" --enable-extpkgs=$OPT_BUILD_DIR/extpkgs --prefix=$OPT_INSTALL_DIR --enable-custom="Built using Hercules-Helper (version: xxxxxxxxxxxxxxxxxxx)" --enable-regina-rexx
            #
            ./config.status --config
            #
            make clean
            time make -j 2 2>&1
            # FIXME 'make check' fails
            # time make check
            #sudo make install
            #
            sudo setcap 'cap_sys_nice=eip' $OPT_INSTALL_DIR/bin/hercules
            sudo setcap 'cap_sys_nice=eip' $OPT_INSTALL_DIR/bin/herclin
            sudo setcap 'cap_net_admin+ep' $OPT_INSTALL_DIR/bin/hercifc
            #
            pwd
            readelf -p .GCC.command.line $OPT_INSTALL_DIR/bin/hercules > hercules-gcc-options.txt

