name: Commit Build
run-name: ${{ github.actor }} is doing a develop build

on:
  push:
    branches:
      - "develop"
      - "workflow"

jobs:
  buildOnLinux:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Get Commit Ref
        run: |
          pwd
          COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_REF: $COMMIT_REF"
          echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV

############

  buildOnMacOS:
    runs-on: macOS-12 # Monterey

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Get Commit Ref
        run: |
          COMMIT_REF=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_REF: $COMMIT_REF"
          echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV
          ls -l

      - name: Install Packages
        run: |
          brew install cmake


############

  buildOnWindows:
    runs-on: windows-2022 # Windows Server 2022

    steps:
      - name: Foo
        run: |
          echo 'Building on Windows Not Implemented Yet'
          echo '$psversiontable...'
          $psversiontable
          write-host "Hello World"
          # echo 'get-computerinfo...'
          # get-computerinfo
          echo "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Get Commit Ref
        run: |
          echo "GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
          #
          # git rev-parse --short $env:GITHUB_SHA
          $env:COMMIT_REF = (git rev-parse --short $env:GITHUB_SHA)
          echo "COMMIT_REF: $env:COMMIT_REF"
          # echo "COMMIT_REF=$COMMIT_REF" >>$GITHUB_ENV
          #

      - name: Command Shell
        shell: cmd
        run: |
          echo "Hello, DOS"
          dir
          echo GITHUB_SHA: %GITHUB_SHA%
          set "git_hash=-gHHHHHHH"
          for /f %%a in ('git rev-parse --short HEAD') do set "COMMIT_REF=%%a"
          echo GIT_HASH: %COMMIT_REF%
          ::
          pushd ..
          dir
          git clone https://github.com/wrljet/hercules-helper-windows.git
          git clone https://github.com/SDL-Hercules-390/hyperion.git
          dir
          popd
          ::
          dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build"
          set HERCULES_HELPER_BUILD_DIR=%cd%\hercules-build
          set HERCULES_HELPER_VCVARS_CMD=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat
          pushd "%HERCULES_HELPER_BUILD_DIR%\sdl-hyperion"
          set HERCULES_BUILD_DIR=%cd%\msvc.AMD64.bin
          call "%HERCULES_HELPER_VCVARS_CMD%"



