name: Test architecture matrix
run-name: ${{ github.actor }} is doing a develop build

#        arch: [armv6l, armv7l, aarch64]
#        - arch: armv6l
#          cpu: arm1176
#          base_image: raspios_lite:latest
#          cpu_info: cpuinfo/raspberrypi_zero_w

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            test `uname -m` = ${{ matrix.arch }}
            grep Model /proc/cpuinfo
            #
            opt_build_dir=~/herctest/hyperion
            opt_install_dir="/usr/local"
            #
            opt_regina_dir="Regina-REXX-3.6"
            opt_regina_tarfile="Regina-REXX-3.6.tar.gz"
            opt_regina_url="http://www.wrljet.com/ibm360/Regina-REXX-3.6.tar.gz"
            git_repo_hercules="https://github.com/SDL-Hercules-390/hyperion.git"
            git_branch_hercules="develop"
            git_commit_hercules=""
            git_repo_extpkgs="https://github.com/SDL-Hercules-390"
            git_branch_extpkgs=""
            #
            pwd
            #
            sudo apt-get install -y git wget time ncat
            sudo apt-get install -y build-essential
            sudo apt-get install -y cmake autoconf automake flex gawk m4
            sudo apt-get install -y libltdl-dev libtool-bin libcap2-bin libbz2-dev zlib1g-dev
            #
            # Clone Hercules-Helper
            git clone https://github.com/wrljet/hercules-helper.git
            ls -l
            #
            mkdir -p $opt_install_dir
            mkdir -p $opt_build_dir
            cd $opt_build_dir
            rm hyperion
            #
            which rexx && true
            export OPT_REGINA_URL="http://www.wrljet.com/ibm360/Regina-REXX-3.6.tar.gz"
            export OPT_REGINA_TARFILE="Regina-REXX-3.6.tar.gz"
            export OPT_REGINA_DIR="Regina-REXX-3.6"
            wget $OPT_REGINA_URL
            tar xfz "$OPT_REGINA_TARFILE"
            pwd
            pushd $OPT_REGINA_DIR
            ./configure --libdir=/usr/lib
            ./config.status --config
            make
            sudo make install
            popd
            #
            ldconfig
            echo "Files:"
            which rexx
            find /usr/local/include -name 'rexx*.h' 2>&1
            #
            # git clone required repos
            cd $opt_build_dir
            rm -rf hyperion
            git clone -b $git_branch_hercules $git_repo_hercules
            cd $opt_build_dir
            rm -rf extpkgs
            mkdir extpkgs
            cd extpkgs/
            rm -rf *
            git clone $git_repo_extpkgs/crypto
            git clone $git_repo_extpkgs/decNumber
            git clone $git_repo_extpkgs/SoftFloat
            git clone $git_repo_extpkgs/telnet
            #
            cd $opt_build_dir/hyperion
            #
            # Check program versions
            util/bldlvlck
            #

