name: Test architecture matrix
run-name: ${{ github.actor }} is doing a develop build

on: [push, pull_request, workflow_dispatch]
#        arch: [armv6l, armv7l, aarch64]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7l, aarch64]
        include:
        - arch: armv6l
          cpu: arm1176
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_zero_w
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        commands: |
            test `uname -m` = ${{ matrix.arch }}
            grep Model /proc/cpuinfo
            #
            pwd
            which git wget gcc || true
            #
            sudo apt-get install git wget time ncat
            sudo apt-get install build-essential
            sudo apt-get install cmake autoconf automake flex gawk m4
            sudo apt-get install libltdl-dev libtool-bin libcap2-bin libbz2-dev zlib1g-dev
            #
            git clone https://github.com/wrljet/hercules-helper.git
            ls -l

